backend/modules/voucher/controllers/CadastroController.php
<?php

namespace backend\modules\voucher\controllers;

use backend\modules\voucher\models\Voucher;
use Yii;
use backend\modules\voucher\models\Cadastro;
use backend\modules\voucher\models\CadastroSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CadastroController implements the CRUD actions for Cadastro model.
 */
class CadastroController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
            ],
        ];
    }

    /**
     * Lists all Cadastro models.
     * @return mixed
     */
    public function actionIndex()
    {
        Voucher::atualizaExpirados();

        $searchModel = new CadastroSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionVoucher()
    {
        return $this->render('voucher', [
            'uuid' => Yii::$app->request->get('uuid')
        ]);
    }


    /**
     * Displays a single Cadastro model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Finds the Cadastro model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cadastro the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cadastro::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/voucher/controllers/ValidarController.php
<?php

namespace backend\modules\voucher\controllers;

use Yii;
use backend\modules\voucher\models\Voucher;
use backend\modules\voucher\models\VoucherSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Pool;
use GuzzleHttp\Client;

/**
 * VoucherController implements the CRUD actions for Voucher model.
 */
class ValidarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'utilizar, estornar' => ['GET'],
                ],
            ],
        ];
    }

    /**
     * Lists all Voucher models.
     * @return mixed
     */
    public function actionIndex()
    {
        Voucher::atualizaExpirados();
        
        $searchModel = new VoucherSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Voucher model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Voucher model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionEmitido($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
             return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionUtilizar($id)
    {
        $model = $this->findModel($id);
        $model->utilizar();
        return $this->redirect(['index', 'VoucherSearch[uuid]'=>$model->uuid]);
    }

    public function actionEstornar($id)
    {
        $model = $this->findModel($id);
        $model->estornar();
        return $this->redirect(['index', 'VoucherSearch[uuid]'=>$model->uuid]);
    }


    /**
     * Finds the Voucher model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Voucher the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Voucher::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    

    
}

backend/modules/voucher/views/validar/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Voucher */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="voucher-form">

	<?php $form = ActiveForm::begin(); ?>

	<?= DetailView::widget( [
		'model'      => $model,
		'attributes' => [
			'uuid',
			'recompensa',
			'criado_em:datetime',
			'expira_em:datetime',
			'status'
		],
	] ) ?>

	<div class="form-group">

		<?php if ($model["status"] == 'emitido') { ?>

		<?= Html::a( "Utilizar", ['utilizar', 'id' => $model["id"]], [ 'class' => 'btn btn-lg btn-success' ] ) ?>
		&nbsp;
		<?= Html::a( 'Estornar', ['estornar', 'id' => $model["id"]], [ 'class' => 'btn btn-lg btn-danger' ] ) ?>
		&nbsp;
		<?php } ?>
		<?= Html::a( 'Voltar', Yii::$app->request->referrer, [ 'class' => 'btn btn-lg btn-default' ] ) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

backend/modules/voucher/views/validar/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\CadastroSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<style>
    .help-block {
        display:none;
    }
</style>

<?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
],
    ['fieldConfig' => ['template' => '{input}']]);
?>

<div class="row">
    <div class="input-group-btn">
        <div class="col-xs-3">
            <?php //echo $form->field($model, 'cpf')->textInput(['maxlength' => 11, 'style'=>'width:100px;', 'class' => 'form-control pull-right', 'placeholder' => 'CPF'])->label(false) ?>
        </div>
        <div class="col-xs-4">
            <?php echo $form->field($model, 'status')->label(false)->dropDownList([ 'emitido' => 'Emitido', 'expirado' => 'Expirado', 'estornado' => 'Estornado', 'utilizado' => 'Utilizado', ], ['prompt' => 'Selecione um status', 'style'=>'width:200px;','onchange'=>'this.form.submit()']) ?>
        </div>
        <div class="col-xs-5">
            <?= Html::submitButton('<i class="fa fa-search"></i>', ['style'=>'float:right;','class' => 'btn btn-default']) ?>
            <?php echo $form->field($model, 'uuid')->textInput(['maxlength' => 36, 'style'=>'width:300px;', 'class' => 'form-control pull-right', 'placeholder' => 'Número do voucher'])->label(false) ?>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/modules/voucher/views/validar/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Voucher */

$this->title = 'Create Voucher';
$this->params['breadcrumbs'][] = ['label' => 'Vouchers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="voucher-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/voucher/views/validar/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\modules\voucher\models\VoucherSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Vouchers';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box">
    <div class="box-header">
        <h3 class="box-title">Filtro</h3>
        <div class="box-tools">
            <?php  echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    </div>

    <div class="box-body table-responsive">

        <?= Yii::$app->session->hasFlash("voucher") ? \insolita\wgadminlte\Alert::widget(Yii::$app->session->getFlash("voucher")) : "";?>

        <?php Pjax::begin(); ?>
        <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'Nome',
                        'format' => 'raw',
                        'value' => function ($model) {
                            return $model->wpUsers->display_name;
//                            return Html::a($model->wpUsers->display_name, ['cadastro/view', 'id' => $model->wpUsers->ID], ['style'=>'font-weight:bolder;']);
                        }
                    ],
                    [
                        'attribute' => 'Número',
                        'format' => 'raw',
                        'value' => function ($model) {
                            switch ( $model["status"] ) {
                                case "emitido":
                                    return Html::a($model["uuid"], ['emitido', 'id' => $model["id"]], ['style'=>'font-weight:bolder;']);
                                    break;
                                case "expirado":
                                    return $model["uuid"];
                                    break;
                                case "estornado":
                                    return $model["uuid"];
                                    break;
                                case "utilizado":
                                    return $model["uuid"];
                                    break;
                            }
                        }
                    ],
                    'criado_em:datetime',
                    'expira_em:datetime',
                    [
                        'attribute' => 'Status',
                        'format' => 'raw',
                        'value' => function ($model) {
                            switch ( $model["status"] ) {
                                case "emitido":
                                    return "<span class=\"label label-primary\">{$model["status"]}</span>";
                                    break;
                                case "expirado":
                                    return "<span class=\"label label-danger\">{$model["status"]}</span>";
                                    break;
                                case "estornado":
                                    return "<span class=\"label label-warning\">{$model["status"]}</span>";
                                    break;
                                case "utilizado":
                                    return "<span class=\"label label-success\">{$model["status"]}</span>";
                                    break;
                            }
                        },
                    ],
                    'atualizado_em:datetime'
                ],
            ]); ?>
        <?php Pjax::end(); ?>
        </div>
    </div>
</div>

backend/modules/voucher/views/validar/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Voucher */

$this->title = 'Voucher';
$this->params['breadcrumbs'][] = ['label' => 'Vouchers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->uuid, 'url' => ['view', 'id' => $model->uuid]];

$class = 'box-primary';
if ($model->status == 'emitido') {
    $class = 'box-primary';
}

if ($model->status == 'utilizado') {
    $class = 'box-success';
}
\bedezign\yii2\audit\web\JSLoggingAsset::register($this);
?>

<div class="box <?= $class; ?>">
    <div class="box-body table-responsive">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

backend/modules/voucher/views/validar/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Voucher */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Vouchers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="voucher-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'recompensa',
            'uuid',
            'status',
            'expira_em',
            'criado_em',
        ],
    ]) ?>

</div>