backend/modules/voucher/models/Cadastro.php
<?php

namespace backend\modules\voucher\models;

use Yii;

/**
 * This is the model class for table "cadastro".
 *
 * @property integer $id
 * @property integer $endereco_id
 * @property integer $sincroniaCompleta
 * @property integer $preCadastro
 * @property string $nome
 * @property string $login
 * @property string $cpf
 * @property string $nascimento
 * @property string $sexo
 * @property string $telefone_celular
 * @property string $telefone_residencial
 * @property string $email
 * @property string $numero
 * @property string $complemento
 * @property string $cep
 * @property string $created
 * @property string $modified
 * @property integer $modifier_id
 * @property integer $creator_id
 *
 * @property Endereco $endereco
 */
class Cadastro extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cadastro';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('central');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['endereco_id', 'sincroniaCompleta', 'preCadastro', 'cpf', 'modifier_id', 'creator_id'], 'integer'],
            [['cpf', 'created', 'modified', 'modifier_id', 'creator_id'], 'required'],
            [['nascimento', 'created', 'modified', 'cnpj'], 'safe'],
            [['sexo'], 'string'],
            [['nome'], 'string', 'max' => 100],
            [['login'], 'string', 'max' => 20],
            [['telefone_celular'], 'string', 'max' => 14],
            [['telefone_residencial'], 'string', 'max' => 13],
            [['email'], 'string', 'max' => 255],
            [['numero'], 'string', 'max' => 10],
            [['complemento'], 'string', 'max' => 120],
            [['cep'], 'string', 'max' => 8],
            [['cpf'], 'unique'],
            [['login'], 'unique'],
            [['endereco_id'], 'exist', 'skipOnError' => true, 'targetClass' => Endereco::className(), 'targetAttribute' => ['endereco_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Usuário que fez o cadastro no sistema. ',
            'endereco_id' => 'Endereco ID',
            'sincroniaCompleta' => 'Sincronia Completa',
            'preCadastro' => 'Pre Cadastro',
            'nome' => 'Nome',
            'login' => 'Login',
            'cpf' => 'Cpf',
            'cnpj' => 'Cnpj',
            'nascimento' => 'Nascimento',
            'sexo' => 'Sexo',
            'telefone_celular' => 'Telefone Celular',
            'telefone_residencial' => 'Telefone Residencial',
            'email' => 'Email',
            'numero' => 'Numero',
            'complemento' => 'Complemento',
            'cep' => 'Cep',
            'created' => 'Created',
            'modified' => 'Modified',
            'modifier_id' => 'Modifier ID',
            'creator_id' => 'Creator ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEndereco()
    {
        return $this->hasOne(Endereco::className(), ['id' => 'endereco_id']);
    }

}

backend/modules/voucher/controllers/CadastroController.php
<?php

namespace backend\modules\voucher\controllers;

use backend\modules\voucher\models\Voucher;
use Yii;
use backend\modules\voucher\models\Cadastro;
use backend\modules\voucher\models\CadastroSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CadastroController implements the CRUD actions for Cadastro model.
 */
class CadastroController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
            ],
        ];
    }

    /**
     * Lists all Cadastro models.
     * @return mixed
     */
    public function actionIndex()
    {
        Voucher::atualizaExpirados();

        $searchModel = new CadastroSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionVoucher()
    {
        return $this->render('voucher', [
            'uuid' => Yii::$app->request->get('uuid')
        ]);
    }


    /**
     * Displays a single Cadastro model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Finds the Cadastro model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cadastro the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cadastro::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/voucher/controllers/ValidarController.php
<?php

namespace backend\modules\voucher\controllers;

use Yii;
use backend\modules\voucher\models\Voucher;
use backend\modules\voucher\models\VoucherSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Pool;
use GuzzleHttp\Client;

/**
 * VoucherController implements the CRUD actions for Voucher model.
 */
class ValidarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'utilizar, estornar' => ['GET'],
                ],
            ],
        ];
    }

    /**
     * Lists all Voucher models.
     * @return mixed
     */
    public function actionIndex()
    {
        Voucher::atualizaExpirados();
        
        $searchModel = new VoucherSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Voucher model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Voucher model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionEmitido($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
             return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionUtilizar($id)
    {
        $model = $this->findModel($id);
        $model->utilizar();
        return $this->redirect(['index', 'VoucherSearch[uuid]'=>$model->uuid]);
    }

    public function actionEstornar($id)
    {
        $model = $this->findModel($id);
        $model->estornar();
        return $this->redirect(['index', 'VoucherSearch[uuid]'=>$model->uuid]);
    }


    /**
     * Finds the Voucher model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Voucher the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Voucher::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    

    
}

backend/modules/voucher/views/cadastro/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Cadastro */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cadastro-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'endereco_id')->textInput() ?>

    <?= $form->field($model, 'sincroniaCompleta')->textInput() ?>

    <?= $form->field($model, 'preCadastro')->textInput() ?>

    <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cpf')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nascimento')->textInput() ?>

    <?= $form->field($model, 'sexo')->dropDownList([ 'M' => 'M', 'F' => 'F', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'telefone_celular')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'telefone_residencial')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'numero')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'complemento')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cep')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created')->textInput() ?>

    <?= $form->field($model, 'modified')->textInput() ?>

    <?= $form->field($model, 'modifier_id')->textInput() ?>

    <?= $form->field($model, 'creator_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/voucher/views/cadastro/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\CadastroSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<style>
    .help-block {
        display:none;
    }
</style>

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        ],
        ['fieldConfig' => ['template' => '{input}']]);
    ?>

<div class="row">
    <div class="input-group-btn">
        <div class="col-xs-4">
            <?php echo $form->field($model, 'cnpj')->label(false)->textInput(['maxlength' => 36, 'style'=>'width:200px;', 'class' => 'form-control pull-right', 'placeholder' => 'CNPJ']) ?>
        </div>
        <div class="col-xs-4">
            <?php echo $form->field($model, 'nome')->label(false)->textInput(['maxlength' => 36, 'style'=>'width:200px;', 'class' => 'form-control pull-right', 'placeholder' => 'Nome do usuário']) ?>
        </div>
        <div class="col-xs-4">
            <?= Html::submitButton('<i class="fa fa-search"></i>', ['style'=>'float:right;','class' => 'btn btn-default']) ?>
            <?php echo $form->field($model, 'cpf')->textInput(['maxlength' => 14, 'style'=>'width:200px;', 'class' => 'form-control pull-right', 'placeholder' => 'CPF'])->label(false) ?>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/modules/voucher/views/cadastro/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Cadastro */

$this->title = 'Create Cadastro';
$this->params['breadcrumbs'][] = ['label' => 'Cadastros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cadastro-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/voucher/views/cadastro/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\data\SqlDataProvider;
use Mask\MaskFactory;
use Mask\MaskTypes;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\voucher\models\CadastroSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cadastros';
$this->params['breadcrumbs'][] = $this->title;

$sql = "
select
  c.id,
  c.nome,
  c.nascimento,
  c.cpf,
  c.sexo,
  (
	SELECT
		e.cnpj
	FROM
		cadastro_empresa ce
		INNER JOIN empresa e ON e.id = ce.empresa_id
	WHERE
		ce.cadastro_id=c.id
  ) as cnpj
from
  cadastro c
";

$sqlCount = "
select
  count(*)
from
  cadastro c
";

if (isset($_GET['CadastroSearch'])) {
    $filtro = [];
    if (isset($_GET['CadastroSearch']['cpf']) && $_GET['CadastroSearch']['cpf'] != "") {
        $cpf = (int) str_replace( ['.','-','/',''], '',  $_GET['CadastroSearch']['cpf']);
        $filtro[] = "cpf like '%{$cpf}%'";
    }
    if (isset($_GET['CadastroSearch']['nome']) && $_GET['CadastroSearch']['nome'] != "") {
        $filtro[] = "nome like '%{$_GET['CadastroSearch']['nome']}%'";
    }
    if (isset($_GET['CadastroSearch']['cnpj']) && $_GET['CadastroSearch']['cnpj'] != "") {
        $cnpj = (int) str_replace( ['.','-','/',''], '',  $_GET['CadastroSearch']['cnpj']);
        $filtro[] = "(SELECT e.cnpj FROM cadastro_empresa ce INNER JOIN empresa e ON e.id = ce.empresa_id WHERE ce.cadastro_id=c.id) like '%{$cnpj}%'";
    }
    if (count($filtro) > 0) {
        $sql .= " WHERE ".join(' AND ',$filtro);
        $sqlCount .= " WHERE ".join(' AND ',$filtro);
    }
}

$totalCount = Yii::$app->central->createCommand($sqlCount)->queryScalar();
$dataProvider = new SqlDataProvider([
    'sql' => $sql,
    'db' => Yii::$app->central,
    'totalCount' => $totalCount,
    'sort' =>false, //to remove the table header sorting
    'pagination' => [
        'pageSize' => 10,
    ],
]);
?>

<!--div class="cadastro-index">
    <h1><?php echo Html::encode($this->title) ?></h1>
</div-->

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Filtro</h3>
        <div class="box-tools">
            <?php  echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    </div>


    <!-- /.box-header -->
    <div class="box-body table-responsive">
        <?php Pjax::begin(['id' => 'cadastro']); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                [
                    'attribute' => 'Nome',
                    'format' => 'raw',
                    'value' => function ($model) {
                        return Html::a($model['nome'], ['view', 'id' => $model['id']]);
                    },
                ],
                [
                    'attribute' => 'Cpf',
                    'format' => 'raw',
                    'value' => function ($model) {
                        $cpf = str_replace( ['-','.','/',''], '', $model['cpf']);
                        $cpf = str_pad( $cpf, 11, 0, STR_PAD_LEFT);
                        return MaskFactory::factory(MaskTypes::MASK_CPF, $cpf)->getMasked();
                    },
                ],
                [
                    'attribute' => 'CNPJ',
                    'format' => 'raw',
                    'value' => function ($model) {
                        if (is_null($model['cnpj']) || empty($model['cnpj'])) return '--';

                        $cnpj = str_replace( ['-','.','/',''], '', $model['cnpj']);
                        $cnpj = str_pad( $cnpj, 14, 0, STR_PAD_LEFT);

                        return MaskFactory::factory(MaskTypes::MASK_CNPJ, str_replace( ['-','.','/',''], '', $cnpj))->getMasked();
                    },
                ],
                'nascimento:date',
                'sexo'
            ],
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <!-- /.box-body -->
</div>

backend/modules/voucher/views/cadastro/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Cadastro */

$this->title = 'Update Cadastro: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cadastros', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cadastro-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/voucher/views/cadastro/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\data\SqlDataProvider;
use yii\widgets\Pjax;
use yii\grid\GridView;
use Mask\MaskFactory;
use Mask\MaskTypes;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Cadastro */

$this->title = $model->nome;
$this->params['breadcrumbs'][] = ['label' => 'Cadastros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab">Informações pessoais</a></li>
        <li><a href="#tab_2" data-toggle="tab">Vouchers</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'nome',
                    'login',
                    [                      // the owner name of the model
                        'label' => 'CPF',
                        'value' => MaskFactory::factory(MaskTypes::MASK_CPF, str_pad( str_replace( ['.','-','/',''], '', $model->cpf),11,0,STR_PAD_LEFT))->getMasked(),
                    ],
                    'nascimento:date',
                    'sexo',
                    [
                        'label' => 'Celular',
                        'value' => MaskFactory::factory(MaskTypes::MASK_TELEFONE, $model->telefone_celular)->getMasked(),
                    ],
                    [
                        'label' => 'Telefone residencial',
                        'value' => MaskFactory::factory(MaskTypes::MASK_TELEFONE, $model->telefone_residencial)->getMasked(),
                    ],
                    'email:email',
                    [
                        'label' => 'Data do cadastro',
                        'format' => 'datetime',
                        'value' => $model->created
                    ]
                ],
            ]) ?>
        </div>
        <div class="tab-pane" id="tab_2">
            <?php
            $sql = "
                SELECT
                    c.nome,
                    ca.pk_cadastro_aplicacao
                FROM
                    cadastro c
                    inner join cadastro_aplicacao ca on ca.cadastro_id=c.id
                    inner join aplicacao a on a.id=2 and ca.aplicacao_id=a.id
                WHERE
                    c.id = {$model->id}
            ";
            $model = Yii::$app->central->createCommand($sql);
            $users_id = $model->queryOne()["pk_cadastro_aplicacao"];


            $totalCount = Yii::$app->portal->createCommand('SELECT COUNT(*) FROM voucher WHERE user_id=:userID', [':userID' => $users_id])->queryScalar();
            $dataProviderVoucher = new SqlDataProvider([
                'sql' => 'SELECT * FROM voucher WHERE user_id=:userID ORDER BY expira_em DESC',
                'db' => Yii::$app->portal,
                'params' => [':userID' => $users_id],
                'totalCount' => $totalCount,
                'sort' =>false, //to remove the table header sorting
                'pagination' => [
                    'pageSize' => 10,
                ],
            ]);
            ?>

            <div class="box-body table-responsive">
                <?php Pjax::begin(); ?>
                <?= GridView::widget([
                    'dataProvider' => $dataProviderVoucher,
                    'columns' => [
                        'recompensa',
                        [
                            'attribute' => 'Número',
                            'format' => 'raw',
                            'value' => function ($model) {
                                switch ( $model["status"] ) {
                                    case "emitido":
                                        return Html::a($model["uuid"], ['validar/emitido', 'id' => $model["id"]], ['style'=>'font-weight:bolder;']);
                                        break;
                                    case "expirado":
                                        return $model["uuid"];
                                        break;
                                    case "estornado":
                                        return $model["uuid"];
                                        break;
                                    case "utilizado":
                                        return $model["uuid"];
                                        break;
                                }
                            }
                        ],
                        'criado_em:datetime',
                        'expira_em:datetime',
                        [
                            'attribute' => 'Status',
                            'format' => 'raw',
                            'value' => function ($model) {
                                switch ( $model["status"] ) {
                                    case "emitido":
                                        return "<span class=\"label label-primary\">{$model["status"]}</span>";
                                        break;
                                    case "expirado":
                                        return "<span class=\"label label-danger\">{$model["status"]}</span>";
                                        break;
                                    case "estornado":
                                        return "<span class=\"label label-warning\">{$model["status"]}</span>";
                                        break;
                                    case "utilizado":
                                        return "<span class=\"label label-success\">{$model["status"]}</span>";
                                        break;
                                }
                            },
                        ],
                        'atualizado_em:datetime'
                    ],
                ]); ?>
                <?php Pjax::end(); ?>
            </div>


        </div>
    </div>
    <!-- /.tab-content -->
</div>

backend/modules/voucher/views/cadastro/voucher.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\data\SqlDataProvider;
use yii\widgets\Pjax;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model backend\modules\voucher\models\Cadastro */

$this->title = "Voucher";
$this->params['breadcrumbs'][] = ['label' => 'Cadastros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="nav-tabs-custom">
    <?php echo $uuid; ?>
</div>